services:
  validator0:
    container_name: validator0
    # build: .
    image: "alloranetwork/allora-chain:v0.2.7"
    environment:
      - NETWORK=edgenet
      - MONIKER=validator0  # Change this to your preferred moniker
      - APP_HOME=/data
    volumes:
      - ./data:/data
      - ./scripts/:/scripts
    ports:
      - "26656-26657:26656-26657"
    user: "0:0"
    entrypoint: /scripts/l1_node.sh
